### ISSUE TITLE
Wich sensor did you use?

### ISSUE THREAD

**Issue by natxopedreira** [gepatto/ofxPiVlxSensor#1]
Hello

I want to use this, what sensor did you tried? Pololu, sparkfun... etc etc.

Also can you comment about the realibility of the sensor measurement reading, is accurate?

Thank you

**Comment by gepatto** [comment]
I used the breakout board from pimoroni  (But the one from polulu might work too)

Accuracy is a lot better than ultrasound. But I don’t know what kind of accuracy you need.
But there’s 2 things that I ran into
- there is wide range  jitter when there is nothing within the range of the sensor
- it doesn’t work well when there’s a lot of infrared light . 
    For  instance sunlight or halogen lamps

**Comment by natxopedreira** [comment]
Thank you!

It was useful
